RELAX(u, v, w)
    if v.d > u.u + w(u,v)   // O(1)
    v.d <- u.d + w(u, v)    // O(1)
    u.pi <- u               // O(1)

DIJKSTRA(G, w, s)
    for each vertex v E G.V // O(n)
        v.d = infinito      // O(1)
        v.pi = NIL          // O(1)
    s.d = 0                 // O(1)
    S <- 0                  // O(1)
    Q <- G.V                // O(1)
    while Q != 0            // O(n)
        u <- EXTRACT_MIN(Q) // O(1)
        S <- S U {u}        // O(1)
        for each vertex v E G.Adj[u]    // O(n)
            RELAX(u,v,w)                // O(1)
